version: "3"

services:
  backend:
    # image: node
    restart: always
    build:
      context: ./sortza-app-project
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks: 
      - default
    depends_on:
      - db
    
  db:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: sortza
    networks: 
      - default

  frontend:
    # image: node
    restart: always
    build:
      context: ./sortza-front
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - default
    depends_on:
      - db

networks:
  default:
    driver: bridge
        
    