version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile : ./Dockerfile
    ports:
      - 3000:3333
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "sortza"
      MYSQL_ROOT_PASSWORD: "password"
    cap_add:
      - SYS_NICE
