version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 3000:3333
    depends_on:
      - db
    networks:
      - sortza
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sortza
    cap_add:
      - SYS_NICE
    networks:
      - sortza
networks:
  sortza:
    driver: bridge